### ISSUE TITLE
bigloo binary for bootstrapping

### ISSUE THREAD

**Issue by ak-1** [manuel-serrano/bigloo#24]
I tried compiling from github but it looks like I need a bigloo binary for bootstrapping:

    /home/.../bigloo/bin/bigloo: not found

It would be great if there were some statically compiled binaries for bootstrapping available.

**Comment by lassik** [comment]
It's typical to download the latest release (at the moment `bigloo4.3f.tar.gz`), build it, and then use the `bin/bigloo` binary built from that release to bootstrap the latest Git master. This is also done for other Scheme implementations.

Sometimes that still doesn't work (if you are unlucky and there have been some breaking changes in the compiler since the release) but usually it does.
