### ISSUE TITLE
'make test' fails for first installation

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/bigloo#8]
INSTALL.md tells us to run `make test` before installing. Currently, this causes recette errors because some files are expected in the installation directories, e.g.
make test
...
make[3] Leaving directory /var/tmp/bigloo4.3c/api/text/recette
cond-expand...ok.
hyphens...ok.
hyphenate-english...ok.
gb2312...*** ERROR:gb2312:
file missing -- /usr/local/lib64/bigloo/4.3c/text/data/gb2312.sch
error.
     ==> provided: [#(#u"Version pas mal resserrée, et je pense ")]
       expected: [#u"Version pas mal resserrée, et je pense "]`

**Comment by manuel-serrano** [comment]
I see where the problem is coming from. Actually, it would be difficult (long and error prone) to modify the installation procedure so that all tests can be ran before Bigloo is fully installed. Instead, what I propose is to split the testing in two parts. Prior to installation, test the compiler and the main library. After the installation, tests the APIs too. I will modify the READMEs and Makefile consequently.

**Comment by svenha** [comment]
Your proposal sounds like a good compromise. Thanks.

**Comment by svenha** [comment]
INSTALL.md tells us now to use `make test` and `make fulltest` at the right time. I tested this on a machine that never had any bigloo installations.
