### ISSUE TITLE
hash table of moderate size exhausts memory

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/bigloo#95]
I used make-hashtable and hashtable-put! for around 10k keys (of size 40 to 250 bytes). Is it expected that this can exhaust your RAM of 64 GB? If not, I can try to generate a test program with test data.

**Comment by manuel-serrano** [comment]
No, for sure it is not! 

What were your keys! Were they strings? I would recommend to use the more recent `create-hashtable` function instead of `make-hashtable` because I think it easier to configure. If you have an example of program that crashes I would be happy to investigate in order to fix that problem. In the meantime I will close this issue and we can re-open it when needed.

**Comment by svenha** [comment]
The issue is 15 months old, and I cannot find the problematic input data anymore. I am sorry.

If I find another problematic data set, I will reopen this issue.

**Comment by manuel-serrano** [comment]
Sure. I understand. My fault.
